name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'unit'
        type: choice
        options:
          - unit
          - integration
          - e2e
      timeUnit:
        description: '选择时间单位'
        required: true
        default: '分钟'
        type: choice
        options:
          - '分钟'
          - '小时'
          - '天'
      email:
        description: 'Email address to notify'
        required: false
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "unit" ]; then  
            echo "Running unit tests" | tee run_output.txt
            echo "output=$(cat run_output.txt)" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.test_type }}" == "integration" ]; then  
            echo "Running integration tests"
          elif [ "${{ github.event.inputs.test_type }}" == "e2e" ]; then  
            echo "Running end-to-end tests"
          fi
          if [ "${{ github.event.inputs.email }}" != "" ]; then  
            echo "Sending email to ${{ github.event.inputs.email }}"
          else
            echo "No email provided"
          fi
      - name: Notify
        run: echo "All tests have completed"
      - name: Generate and Display Build Output Table in Summary
        run: |
          echo "| Email | Subject | From | Time | Type |" > build_table.md
          echo "|--------------|-----------------|----------------|---------------|-------------|" >> build_table.md

          build_output="Success" # This would typically be parsed from build_output.txt
          run_output="Success" # This would typically be parsed from run_output.txt

          echo "| wzj121388@gmail.com | 主题 | xxx@gmail.com | 2024年7月25日 | 收件箱 |" >> build_table.md


          cat build_table.md

          echo "# CheckGmail" >> $GITHUB_STEP_SUMMARY
          cat build_table.md >> $GITHUB_STEP_SUMMARY