name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: true
        default: 'unit'
        type: choice
        options:
          - unit
          - integration
          - e2e
      timeUnit:
        description: '选择时间单位'
        required: true
        default: '分钟'
        type: choice
        options:
          - '分钟'
          - '小时'
          - '天'
      email:
        description: 'Email address to notify'
        required: false
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.test_type }}" == "unit" ]; then  
            echo "Running unit tests"
          elif [ "${{ github.event.inputs.test_type }}" == "integration" ]; then  
            echo "Running integration tests"
          elif [ "${{ github.event.inputs.test_type }}" == "e2e" ]; then  
            echo "Running end-to-end tests"
          fi
          if [ "${{ github.event.inputs.email }}" != "" ]; then  
            echo "Sending email to ${{ github.event.inputs.email }}"
          else
            echo "No email provided"
          fi
      - name: Notify
        run: echo "All tests have completed"
      - name: Generate and Display Build Output Table
        run: |
          echo "| Step | Output |" > build_table.md
          echo "|------|--------|" >> build_table.md
          while IFS= read -r line; do
            echo "| Build Step | \`$line\` |" >> build_table.md
          done < build_output.txt
          cat build_table.md